version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: dummy_db_container
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "mariadb"
      MARIADB_DATABASE: "dummy_db"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data: