/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dados para atualizar um cliente pessoa física
 */
export interface ClienteFisicoUpdateRequest {
  /**
   * Nome completo
   */
  nome: string;
  /**
   * E-mail do cliente
   */
  email?: string;
  /**
   * Status do cliente
   */
  estaAtivo?: boolean;
}

