/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dados de cliente pessoa jurídica para relatório
 */
export interface ClienteJuridicoReportResponse { 
    /**
     * ID do cliente
     */
    id?: number;
    /**
     * Tipo do cliente
     */
    tipo?: ClienteJuridicoReportResponse.TipoEnum;
    /**
     * Razão Social
     */
    razaoSocial?: string;
    /**
     * CNPJ
     */
    cnpj?: string;
    /**
     * Inscrição Estadual
     */
    inscricaoEstadual?: string;
    /**
     * E-mail do cliente
     */
    email?: string;
    /**
     * Status do cliente
     */
    estaAtivo?: boolean;
    /**
     * Data de criação da empresa
     */
    dataCriacaoEmpresa?: string;
    /**
     * Data de criação do registro
     */
    createdAt?: string;
}
export namespace ClienteJuridicoReportResponse {
    export const TipoEnum = {
        Fisica: 'FISICA',
        Juridica: 'JURIDICA'
    } as const;
    export type TipoEnum = typeof TipoEnum[keyof typeof TipoEnum];
}


