/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnderecoUpdateRequest } from './enderecoUpdateRequest';


/**
 * Dados para atualizar um cliente pessoa jurídica
 */
export interface ClienteJuridicoUpdateRequest { 
    /**
     * Razão Social
     */
    razaoSocial: string;
    /**
     * Inscrição Estadual
     */
    inscricaoEstadual?: string;
    /**
     * E-mail do cliente
     */
    email?: string;
    /**
     * Data de criação da empresa
     */
    dataCriacaoEmpresa?: string;
    /**
     * Status do cliente
     */
    estaAtivo?: boolean;
    /**
     * Lista de endereços do cliente
     */
    enderecos: Array<EnderecoUpdateRequest>;
}

