/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dados de cliente pessoa física para relatório
 */
export interface ClienteFisicoReportResponse { 
    /**
     * ID do cliente
     */
    id?: number;
    /**
     * Nome completo
     */
    nome?: string;
    /**
     * CPF (formato: 000.000.000-00)
     */
    cpf?: string;
    /**
     * RG (sem formatação)
     */
    rg?: string;
    /**
     * E-mail do cliente
     */
    email?: string;
    /**
     * Data de nascimento
     */
    dataNascimento?: string;
    /**
     * Status do cliente
     */
    estaAtivo?: boolean;
    /**
     * Data de criação
     */
    createdAt?: string;
}

