/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {EnderecoWithinClienteCreateRequest} from './enderecoWithinClienteCreateRequest';


/**
 * Dados para criar um cliente pessoa física
 */
export interface ClienteFisicoCreateRequest {
  /**
   * CPF (formato: 000.000.000-00)
   */
  cpf: string;
  /**
   * Nome completo
   */
  nome: string;
  /**
   * RG (sem formatação)
   */
  rg: string;
  /**
   * E-mail do cliente
   */
  email?: string;
  /**
   * Data de nascimento
   */
  dataNascimento: string;
  /**
   * Lista de endereços do cliente
   */
  enderecos: Array<EnderecoWithinClienteCreateRequest>;
}

