/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnderecoCreateRequest } from './enderecoCreateRequest';


/**
 * Dados para criar um cliente pessoa jurídica
 */
export interface ClienteJuridicoCreateRequest { 
    /**
     * CNPJ (formato: 00.000.000/0000-00)
     */
    cnpj: string;
    /**
     * Razão Social
     */
    razaoSocial: string;
    /**
     * Inscrição Estadual (sem formatação)
     */
    inscricaoEstadual: string;
    /**
     * E-mail do cliente
     */
    email?: string;
    /**
     * Data de criação da empresa
     */
    dataCriacaoEmpresa: string;
    /**
     * Lista de endereços do cliente
     */
    enderecos: Array<EnderecoCreateRequest>;
}

