/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dados para criar um endereço
 */
export interface EnderecoWithinClienteCreateRequest { 
    /**
     * Logradouro
     */
    logradouro: string;
    /**
     * Número
     */
    numero: number;
    /**
     * CEP
     */
    cep: string;
    /**
     * Bairro
     */
    bairro: string;
    /**
     * Telefone
     */
    telefone?: string;
    /**
     * ID do município (IBGE)
     */
    municipioId: number;
    /**
     * Indica se é o endereço principal
     */
    principal?: boolean;
    /**
     * Complemento
     */
    complemento?: string;
}

