/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dados resumidos de endereço para listas
 */
export interface EnderecoListResponse { 
    /**
     * ID do endereço
     */
    id?: number;
    /**
     * Logradouro
     */
    logradouro?: string;
    /**
     * Número
     */
    numero?: number;
    /**
     * CEP
     */
    cep?: string;
    /**
     * Bairro
     */
    bairro?: string;
    /**
     * Cidade
     */
    cidade?: string;
    /**
     * Estado
     */
    estado?: string;
    /**
     * ID do município (IBGE)
     */
    municipioId?: number;
    /**
     * ID do cliente dono do endereço
     */
    clienteId?: number;
    /**
     * Indica se é o endereço principal
     */
    principal?: boolean;
}

