/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dados para atualizar um endereço
 */
export interface EnderecoUpdateRequest { 
    /**
     * Logradouro
     */
    logradouro?: string;
    /**
     * Número
     */
    numero?: number;
    /**
     * CEP
     */
    cep?: string;
    /**
     * Bairro
     */
    bairro?: string;
    /**
     * Telefone
     */
    telefone?: string;
    /**
     * ID do município (IBGE)
     */
    municipioId?: number;
    /**
     * Endereço principal
     */
    principal?: boolean;
    /**
     * Complemento
     */
    complemento?: string;
}

