/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dados completos de um endereço
 */
export interface EnderecoResponse { 
    /**
     * ID do endereço
     */
    id?: number;
    /**
     * Logradouro
     */
    logradouro?: string;
    /**
     * Número
     */
    numero?: number;
    /**
     * CEP
     */
    cep?: string;
    /**
     * Bairro
     */
    bairro?: string;
    /**
     * Telefone
     */
    telefone?: string;
    /**
     * Estado
     */
    estado?: string;
    /**
     * Cidade
     */
    cidade?: string;
    /**
     * Indica se é o endereço principal
     */
    principal?: boolean;
    /**
     * Complemento
     */
    complemento?: string;
    /**
     * ID do cliente dono do endereço
     */
    clienteId?: number;
    /**
     * Data de criação
     */
    createdAt?: string;
    /**
     * Data da última atualização
     */
    updatedAt?: string;
}

