/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dados de um município
 */
export interface MunicipioDTO { 
    /**
     * ID IBGE
     */
    id?: number;
    /**
     * Nome
     */
    nome?: string;
    /**
     * Sigla da UF
     */
    ufSigla?: string;
}

