/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrgSpringdocCoreConvertersModelsPageable { 
    page?: number;
    size?: number;
    sort?: Array<string>;
}

