/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageableObject} from './pageableObject';
import {SortObject} from './sortObject';
import {ClienteFisicoListResponse} from './clienteFisicoListResponse';


export interface PageClienteFisicoListResponse {
  totalPages?: number;
  totalElements?: number;
  size?: number;
  content?: Array<ClienteFisicoListResponse>;
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  pageable?: PageableObject;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}

