/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dados de uma unidade federativa
 */
export interface UnidadeFederativaDTO { 
    /**
     * ID IBGE
     */
    id?: number;
    /**
     * Sigla
     */
    sigla?: string;
    /**
     * Nome
     */
    nome?: string;
}

