/**
* OpenAPI definition
*
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

import { Provider, NgModule, ModuleWithProviders } from "@angular/core";
import { Configuration, ConfigurationParameters } from './configuration';
import { BASE_PATH } from './variables';

// For Angular 14: Use Provider[] instead of EnvironmentProviders
export function provideApi(configOrBasePath: string | ConfigurationParameters): Provider[] {
return [
typeof configOrBasePath === "string"
? { provide: BASE_PATH, useValue: configOrBasePath }
: {
provide: Configuration,
useValue: new Configuration({ ...configOrBasePath }),
},
];
}
