/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InjectionToken } from '@angular/core';

export const BASE_PATH = new InjectionToken
<string>('basePath');
