/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';


// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';


@Injectable({
  providedIn: 'root'
})
export class ArquivoService extends BaseService {

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
    super(basePath, configuration);
  }

  /**
   * Exportar lista de clientes físicos para PDF
   * @endpoint get /v1/export/clientes/fisicos/pdf
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public arquivoExportClientesFisicosToPdf(observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<string>;
  public arquivoExportClientesFisicosToPdf(observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<HttpResponse<string>>;
  public arquivoExportClientesFisicosToPdf(observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<HttpEvent<string>>;
  public arquivoExportClientesFisicosToPdf(observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<any> {

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/pdf'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/v1/export/clientes/fisicos/pdf`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Exportar lista de clientes físicos para XLSX
   * @endpoint get /v1/export/clientes/fisicos/xlsx
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public arquivoExportClientesFisicosToXlsx(observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<string>;
  public arquivoExportClientesFisicosToXlsx(observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpResponse<string>>;
  public arquivoExportClientesFisicosToXlsx(observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpEvent<string>>;
  public arquivoExportClientesFisicosToXlsx(observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<any> {

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/v1/export/clientes/fisicos/xlsx`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Exportar lista de clientes jurídicos para PDF
   * @endpoint get /v1/export/clientes/juridicos/pdf
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public arquivoExportClientesJuridicosToPdf(observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<string>;
  public arquivoExportClientesJuridicosToPdf(observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<HttpResponse<string>>;
  public arquivoExportClientesJuridicosToPdf(observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<HttpEvent<string>>;
  public arquivoExportClientesJuridicosToPdf(observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<any> {

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/pdf'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/v1/export/clientes/juridicos/pdf`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Exportar lista de clientes jurídicos para XLSX
   * @endpoint get /v1/export/clientes/juridicos/xlsx
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public arquivoExportClientesJuridicosToXlsx(observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<string>;
  public arquivoExportClientesJuridicosToXlsx(observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpResponse<string>>;
  public arquivoExportClientesJuridicosToXlsx(observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpEvent<string>>;
  public arquivoExportClientesJuridicosToXlsx(observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<any> {

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/v1/export/clientes/juridicos/xlsx`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Exportar endereços de um cliente para PDF
   * @endpoint get /v1/export/clientes/{clienteId}/enderecos/pdf
   * @param clienteId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public arquivoExportEnderecosToPdf(clienteId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<string>;
  public arquivoExportEnderecosToPdf(clienteId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<HttpResponse<string>>;
  public arquivoExportEnderecosToPdf(clienteId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<HttpEvent<string>>;
  public arquivoExportEnderecosToPdf(clienteId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/pdf',
    context?: HttpContext
  }): Observable<any> {
    if (clienteId === null || clienteId === undefined) {
      throw new Error('Required parameter clienteId was null or undefined when calling arquivoExportEnderecosToPdf.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/pdf'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/v1/export/clientes/${this.configuration.encodeParam({
      name: "clienteId",
      value: clienteId,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}/enderecos/pdf`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Exportar endereços de um cliente para XLSX
   * @endpoint get /v1/export/clientes/{clienteId}/enderecos/xlsx
   * @param clienteId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public arquivoExportEnderecosToXlsx(clienteId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<string>;
  public arquivoExportEnderecosToXlsx(clienteId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpResponse<string>>;
  public arquivoExportEnderecosToXlsx(clienteId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpEvent<string>>;
  public arquivoExportEnderecosToXlsx(clienteId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<any> {
    if (clienteId === null || clienteId === undefined) {
      throw new Error('Required parameter clienteId was null or undefined when calling arquivoExportEnderecosToXlsx.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/v1/export/clientes/${this.configuration.encodeParam({
      name: "clienteId",
      value: clienteId,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}/enderecos/xlsx`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Baixar template XLSX para importação de clientes físicos
   * @endpoint get /v1/export/clientes/fisicos/template
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public arquivoTemplateClientesFisicos(observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<string>;
  public arquivoTemplateClientesFisicos(observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpResponse<string>>;
  public arquivoTemplateClientesFisicos(observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpEvent<string>>;
  public arquivoTemplateClientesFisicos(observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<any> {

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/v1/export/clientes/fisicos/template`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Baixar template XLSX para importação de clientes jurídicos
   * @endpoint get /v1/export/clientes/juridicos/template
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public arquivoTemplateClientesJuridicos(observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<string>;
  public arquivoTemplateClientesJuridicos(observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpResponse<string>>;
  public arquivoTemplateClientesJuridicos(observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpEvent<string>>;
  public arquivoTemplateClientesJuridicos(observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<any> {

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/v1/export/clientes/juridicos/template`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Baixar template XLSX para importação de endereços
   * @endpoint get /v1/export/enderecos/template
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public arquivoTemplateEnderecos(observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<string>;
  public arquivoTemplateEnderecos(observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpResponse<string>>;
  public arquivoTemplateEnderecos(observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<HttpEvent<string>>;
  public arquivoTemplateEnderecos(observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    context?: HttpContext
  }): Observable<any> {

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/v1/export/enderecos/template`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<string>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

}
